name: Convert and Publish Obsidian MD Files

on:
  push:
    paths:
      - '**/*.md'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Convert MD to HTML
      run: |
        mkdir -p html
        for file in $(find . -type f -name '*.md'); do
          filename=$(basename "$file" .md)
          htmlname=$(echo "$filename" | tr -c '[:alnum:]' '-' | tr -s '-').html
          pandoc "$file" -o "./html/$htmlname"
        done

    - name: Add basic HTML structure
      run: |
        for file in $(find ./html -type f -name '*.html'); do
          basename=$(basename "$file" .html)
          cat <<EOF > temp.html
<!DOCTYPE html>
<html>
<head>
  <title>$basename</title>
  <style>
    body { font-family: Arial, sans-serif; margin: 0; padding: 0; }
    .sidebar { width: 200px; float: left; background: #f4f4f4; padding: 10px; height: 100vh; }
    .content { margin-left: 220px; padding: 20px; }
    footer { margin-top: 20px; text-align: center; background: #f4f4f4; padding: 10px; }
  </style>
</head>
<body>
  <div class="sidebar">
    <h2>Sidebar</h2>
    <p>Links or other content</p>
  </div>
  <div class="content">
    <h1>$basename</h1>
EOF
          cat "$file" >> temp.html
          cat <<EOF >> temp.html
  </div>
  <footer>
    <p>Footer content</p>
  </footer>
</body>
</html>
EOF
          mv temp.html "$file"
        done

    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add .
        if ! git diff-index --quiet HEAD; then
          git commit -m 'Convert MD files to HTML and publish'
          git push
        else
          echo "No changes to commit."
        fi
