name: Convert and Publish Obsidian MD Files

on:
  push:
    paths:
      - '**/*.md'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Convert MD to HTML
      run: |
        mkdir -p html
        for file in $(find . -type f -name '*.md'); do
          filename=$(basename "$file" .md)
          htmlname=$(echo "$filename" | tr -c '[:alnum:]' '-' | tr -s '-').html
          pandoc "$file" -o "./html/$htmlname"
        done

    - name: Add basic HTML structure
      run: ./.github/scripts/add_html_structure.sh

    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add .
        if ! git diff-index --quiet HEAD; then
          git commit -m 'Convert MD files to HTML and publish'
          git push
        else
          echo "No changes to commit."
        fi
